### ISSUE TITLE
Unix ARDrone3PilotingStateAltitudeChangedCallback is not working.

### ISSUE THREAD

**Issue by deepakilango** [Parrot-Developers/ARSDKBuildUtils#20]
Hi,

We are using unix sdk. we wanted to measure when the altitude is changed. We used the ARCOMMANDS_Decoder_SetARDrone3PilotingStateAltitudeChangedCallback to set a call back function. Callback function definition was as follows. ARDrone3PilotingStateAltitudeChangedCallback(double altitude, void *custom)

But the call back method is not called. Is there something else we need to enable before receiving these call backs? (Is there a flag to enable navdata)

Thanks,
Deepak

**Comment by murariuroger** [comment]
Hi,
Same problem for me when I try to get the battery state. The callback functions is not called.
