### ISSUE TITLE
ARDroneSDK3 video streaming

### ISSUE THREAD

**Issue by skaarjbg** [Parrot-Developers/ARSDKBuildUtils#22]
Hello,

I'm trying to initiate video stream between Parrot Bebop drone and android phone using ARStreamReader.

My constructor params are : 
        reader = new ARStreamReader(manager, //ARNetworkManager
                netConfig.getVideoDataIOBuffer(),     
                netConfig.getVideoAckIOBuffer(),
                data,
                listener,
                videoFragmentSize,
                netConfig.getDefaultVideoMaxAckInterval());

netConfig.getVideoDataIOBuffer() returns iobufferD2cArstreamData = ARNetworkALManager.ARNETWORKAL_MANAGER_WIFI_ID_MAX / 2) - 3; - copied from Samples/Android/FreeFlight3Extract/ARDrone3ARNetworkConfig.java

netConfig.getVideoAckIOBuffer() returns iobufferC2dArstreamAck = 13; - again copied from Samples/Android/FreeFlight3Extract/ARDrone3ARNetworkConfig.java

data is ARNativeData data = new ARNativeData(1024);

videoFragmentSize is 1000, as defined in the JSON, received on discovery.
netConfig.netConfig.getDefaultVideoMaxAckInterval() returns 5.

So, with this configuration, when starting the ARStreamReader runnables, in new threads, as per the class description, the following error occurs:
 E/ARSTREAM_Reader﹕ 12:13:37:204 | ARSTREAM_Reader_RunDataThread:369 - Error while reading stream data: Given IOBuffer identifier is unknown

Could you please review my configuration and point out to me any errors?

Regards,
Petar

**Comment by CesarRN** [comment]
Hello skaarjbg

Can you share your method?

I am developing an iOS app and I´m trying to mix the Unix example and the RollingSpiderDemo.

Do you check the parameters about in the unix-example?

Thanks!

**Comment by skaarjbg** [comment]
Hello,

I'm instantiating an ARStreamReader which is an android wrapper  over the ARSTREAM_Reader_New(....) method.....i think.

My params seem the same as the ones, used in the UNIX example, but I might be overlooking something.

Regards, 
Petar

**Comment by CesarRN** [comment]
Hello again.

I think I have a progress.
My code stops here: "frameCompleteCallback"

What should I do with the "uint8_t *frame, uint32_t frameSize" in an iOS app?

I don´t know nothing about video manage  :/


Thanks!

**Comment by djavan-bertrand** [comment]
Hi, 

On a Bebop, you have an h264 frame. On a JumpingSumo you have a mjpeg frame.
You will need to decode the frame. FFMpeg can do that for you, there are also other decoders.

**Comment by CesarRN** [comment]
Hello Djavan, I am not have experience in video management.

Could you give us more information about the frame management?

Thanks in advance.

**Comment by skaarjbg** [comment]
Hello Djavan,

Could you please tell me what causes this error, and perhaps a way to fix it.

E/ARSTREAM_Reader﹕ 12:13:37:204 | ARSTREAM_Reader_RunDataThread:369 - Error while reading stream data: Given IOBuffer identifier is unknown

Thanks & regards,
Petar

**Comment by dk683** [comment]
Hello. Were you able to decode H264 frame? Through referencing the Unix JumpingSumoReceiveStream example, I am able to receive H264 frame. But in order to display/save the frame, I think I need to decode it. 

I found this website (http://ardrone-ailab-u-tokyo.blogspot.jp/2012/07/212-ardrone-20-video-decording-ffmpeg.html) for decoding ARDrone 2.0. but I am not sure whether this will be useful for bebop.

**Comment by ChengYaoWang** [comment]
Hello skaarjbg,
In my current project, I'm also trying to get video stream from Parrot Bebop drone on my android phone. Right now I only developed a controller Android app for my Rolling Spider by using ARDroneSDK3. It work perfectly. 

I'd would like to know if you solve your problem. If not, is there any way to show the video stream from Bebop drone on android smartphones. I hope i can get the answer before I buy a Bebop drone :) 

Thanks & regards,
Eric
