### ISSUE TITLE
ARSAL not building (Unix)

### ISSUE THREAD

**Issue by LordOfTheTrees** [Parrot-Developers/ARSDKBuildUtils#23]
Hey, I'm having a problem with the ARSAL library when I try to build the libraries. Specifically, all other libraries build correctly but ARSAL. Strangely, when I build just that library with the "./SDK3Build.py -l ARSAL" command it gives this error as the root of the problem: 

aclocal: error: configure.ac:8: file '../../ARSDKBuildUtils/Utils/m4/ARSDK.m4' does not exist

However, this makes no sense, as all the other libraries built correctly, and it appears as though this is something used by all libraries built.

Help would be appreciated,

-Andrew

**Comment by N-Bz** [comment]
Hi,

Could you provide a complete log (inseally as [gist](https://gist.github.com/)) of:
1> The `./CheckEnv.py` command
2> The `./SDK3Build.py -t Unix --nogit` (assuming the compilation fails for Unix target, else replace with the proper target)

Regards,
Nicolas.

**Comment by LordOfTheTrees** [comment]
Hey, thanks for the help.

I have uploaded the logs of both as public gists on my account. I think the source of the issue is the call of autoconf in the bootstrap of the ARSAL library build folder. I'm not familiar with autoconf though, so i don't know why it is not seeing the file that is clearly there.

https://gist.github.com/LordOfTheTrees

-Andrew

**Comment by N-Bz** [comment]
Hi,

Thanks for the logs.

You should not have to run the build script as superuser, as it may cause issues with permissions of generated files. I'm not sure if it's the source of your issue, but I wanted to point it out.

In your case, the only correctly built libraries (curl and json) does not depends on ARSDK.m4 file.

Could you check the access rights for the m4 file ? I know that aclocal uses the "does not exist" error for any "can't read" issue, even if the file actually exists but has wrong permissions.

Regards,
Nicolas.

**Comment by LordOfTheTrees** [comment]
Hey,

So pursuant to your warning about building with sudo, created a second installation without using sudo. I have also uploaded this log dump from the installation.

On the question of the permissions, here are the permissions of the m4 file in my sudo installation, followed by the permissions in my new installation:

-rwxrwxrwx@ 1 CRA  staff  4361 Mar 16 04:09 ARSDK.m4

-rwxr-xr-x@ 1 CRA  staff  4361 Mar 16 04:09 ARSDK.m4

In all groups, there is read and execute permissions, so I don't think this is the issue.

-Andrew

**Comment by darryljackman** [comment]
Also have this issue, wasn't a problem with earlier release of this SDK, first happened when trying to build the 64bit compatible revision.

**Comment by kamhagh** [comment]
Anyfix? im not running SU and i this is the log:
https://gist.github.com/anonymous/8cfb507602bd6799d74d
i have a 64-bit Ubuntu 14.04LTS 
everything goes fine expect arsal for unix, it goes ok for ios and android (which i installed because i forgot to put -t Unix!)

**Comment by LeThaiSon** [comment]
Also having the same issue, anyfix?

**Comment by LeThaiSon** [comment]
aclocal: error: configure.ac:8: file '../../ARSDKBuildUtils/Utils/m4/ARSDK.m4' does not exist
  I found that the error because the folder named "ARSDKBuildUtils-ARSDK3_version_3_1_0" so that Ubuntu couldn't find the .m4 file! Rename it into "ARSDKBuildUtils" and it fixed the error.
