### ISSUE TITLE
Bebop OS

### ISSUE THREAD

**Issue by murariuroger** [Parrot-Developers/ARSDKBuildUtils#26]
Can I put a script on my Bebop using ftp and then run it using telnet? I'm thinking to put it in /media/ftp/internal_000/my_script. Does the Bebop have a checksum and detects there is a binary that is not part of the OS? I don't want to crash my Bebop OS.
   I'm a student working on a project. Have a deadline over a few weeks. I will appreciate a quick answer. 
   I called the custom service and they suggested to open an issue here.

**Comment by djavan-bertrand** [comment]
Hi, 
There is no problem running custom scripts on the Bebop. It will run. 
Just be sure about what you are running (your script shouldn't delete private files or something like that) ;)

Best regards, 
Djavan

**Comment by murariuroger** [comment]
Thank you Djavan

**Comment by djavan-bertrand** [comment]
In addition to that, please note that telnet support may change in the future updates.
