### ISSUE TITLE
Bebop drone taking picture

### ISSUE THREAD

**Issue by skaarjbg** [Parrot-Developers/ARSDKBuildUtils#27]
Hello,

Can you post a sample extract for taking a picture with the Bebop drone and transfering it on an different device. I couldn't quite figure it out from the documentation (I'm trying to accomplish this by using ARCommand with the setARDrone3MediaRecordPicture() method, but without much success for now.)

Thanks & regards,
Petar

**Comment by djavan-bertrand** [comment]
Hi, 

Please see [this related issue](https://github.com/ARDroneSDK3/Samples/issues/29#issuecomment-84709358). 
Don't hesitate to ask again if it does not fully answer your question.

Regards, 
Djavan

**Comment by skaarjbg** [comment]
Hello Djavan,

I've modeled an android class according to your example, but when I try to create MediasDownloader I get this exception: 

04-07 15:01:42.054    4195-4195/co.flyver.parrotsdktest W/System.err﹕ ARDataTransferException [System error]
04-07 15:01:42.069    4195-4195/co.flyver.parrotsdktest W/System.err﹕ at com.parrot.arsdk.ardatatransfer.ARDataTransferMediasDownloader.createMediasDownloader(ARDataTransferMediasDownloader.java:100)

This is my code for initializing the mediaDownloader:

        try {
            ftpQueueManager = new ARUtilsManager();
            ftpListManager = new ARUtilsManager();
        } catch (ARUtilsException e) {
            e.printStackTrace();
        }
        ftpQueueManager.initWifiFtp(IP, PORT, LOGIN, "");
        ftpListManager.initWifiFtp(IP, PORT, LOGIN, "");

        mediasDownloader = manager.getARDataTransferMediasDownloader();
        try {
            mediasDownloader.createMediasDownloader(ftpListManager, ftpQueueManager, REMOTE_PATH, LOCAL_PATH);
        } catch (ARDataTransferException e) {
            e.printStackTrace();
        }

**Comment by djavan-bertrand** [comment]
Hi, 

Normally you're good with this code. 
**Be sure to have set in your manifest file the permission to write in the external storage.**

Hope this helps,
Djavan
