### ISSUE TITLE
Support for getting pud logfiles out of the drone

### ISSUE THREAD

**Issue by KenthJ** [Parrot-Developers/ARSDKBuildUtils#28]
Hi

I have a Bebop drone and a SkyController, and I’m really happy about this fun toy.

I have a little suggestion for you, I hope you can find the time to read this, even though it’s a bit long.

I have made a tool in my spare time for converting the binary pud logfiles from the Bebop into some useful formats, I call the tool Pud2GpxKmlCsv.

The tool generates both a csv file for Excel and a kml file for Google Earth, so the flight can be seen in both 2D and 3D in Google Earth.

The most useful functionality of this tool is that it generates a gpx file.

This gpx file can be used for Garmin Virb Edit, which is a free tool developed by Garmin, to generate GPS overlays on the videos from the Bebop.

These GPS overlays can show the user a GPS track, altitude, velocity, date time, orientation of the drone, pitch and roll, battery level of the Bebop and the distance between the controller and the Bebop.

See the website below for further info of the tool, screendumps and example of videos with these overlays.
https://sites.google.com/site/pud2gpxkmlcsv/

For some of the values, I more or less directly copy the values from the pud files directly to the gpx file, but there are also some more advanced calculations done in the tool, for an example the distance from controller to the Bebop, which can also be converted to feets instead of meters. Especially complex is the calculation for orientation of the drone and the pitch and roll of the drone which is converted from the Theta, Alpha and Phi into acceleration X, Y and Z in the gpx file.
The gpx file format does not support data fields for ‘Distance to drone’ and ‘Battery level’, but I have found a workaround for that.

Furthermore the tool can automatically install the templates used for Garmin Virb Edit or the user can make his own templates. I have tried making this tool as easy to use as possible,

I have made this tool only for fun, and I have no intention on earning money on it. I have placed the tool on a public available website for free download.

I have posted a link to this tool on the Parrot Bebop US forum, and until now this thread has been read close to 2.500 times, and a lot of people are pretty happy about this tool.

I have also planned to announce the tool on the Parrot Bebop Owners Group on Facebook in the near future.
I believe this tool adds a lot of value for the users, which found it interesting to get these details on the videos before they post it on YouTube.

The only problem, and the reason for this mail, is that it is very hard to get these pud files out of the drone.
As soon as the drone has landed, the FreeFlight app removes the pud file from the drone and sends it to the drone academy.

With this thread I want to hear, if it would be possible for you in a future software update of the Bebop, to make it easier for the user to get a copy of the pud files.

I was thinking of something like the following:
When you connect a PC via USB to the Bebop, you will get a drive mapped on your PC containing the media files like videos and pictures from the flight.

In this drive it could be nice to have a separate folder, for example called “Pud Files” which contains the latest pud files.
It will only require some fairly simple code added to the Bebop software, so just before the pud file is moved to the phone or tablet by FreeFlight app, a copy of the file is copied into this folder.

Furthermore, to prevent that these pud files eventually fills up the entire memory of the Bebop, the files older than for an example 10 days could be deleted automatically by the software.

Another solution is to make the change in the FreeFlight app, so when the pud files are moved to the Drone Academy, it will also place a copy on the phone / tablet in a location where the user can easily access it. (I would prefer the first solution)

I hope to hear from you regarding this.

Thanks for your time

Best Regards
Kenth Jensen, Denmark

**Comment by djavan-bertrand** [comment]
Hi Kenth, 

We are taking in consideration your needs. We are thinking about how to get the best solution for every one.

I will notify you through this issue when a solution will be chosen / implemented.

Thanks for your remarks, 
Djavan

**Comment by KenthJ** [comment]
Hi Djavan

Thanks a lot for your fast response, and I'm really happy to hear that you are willing to make it easier to get the pud files out.

I fully agree that a solution shall make it easier for everyone, not only for me.
I do believe my suggestion with placing them in a subfolder under the mapped drive, where the user normally gets the video out of the drone, when connecting a usb cable to the drone, will be a easy solution for everybody, but if you can find an even better solution, I will be more than happy about that too.

Another small issue, in the latest couple of sw versions the latitude and longitude of the controller has been empty (500, 500) even though SkyController do have a valid GPS fix, this worked fine in earlier versions.
I use this information for calculating distance between the drone and the pilot.

Best regards
Kenth Jensen

**Comment by djavan-bertrand** [comment]
Yes, the not valid gps position is set when the location is not accurate enough. 
We set the minimum accuracy to 12 meters. Beyond this accuracy, (500, 500) will be returned.

Best regards, 
Djavan

**Comment by frank1238** [comment]
djavan-bertrand: yes, but in the latest firmware versions (1.98.x), the position of the SKC is ALWAYS reported as 500,500. Even if the GPS fix is good and green. Moreover, RTH is since 1.98.x to the startup position, and never to the SKC. This was correct in 1.32 and 1.33!

**Comment by KenthJ** [comment]
I fully agree with Frank, the performance of the GPS must be really poor if the accuracy newer goes below 12 meters.
I also only fly with my drone when both drone and skyController has green GPS lock, but lat+lon for controller is always reported as 500, 500.
Furthermore the RTH works pretty bad, even after 10 minutes of flying with green GPS lock, RTH can still fly up to 10 meters wrong.

**Comment by KenthJ** [comment]
Hi again Djavan

Have you agreed on a solution for this, and any ideas of time frame of when it will be implemented/ released.

Thanks in advance.
Br
Kenth

**Comment by djavan-bertrand** [comment]
Hi, 

We will try to release a solution at the end of this summer. We can't discuss the method yet, but we are taking your remarks in consideration. 
Thanks.

Best regards, 
Djavan

**Comment by KenthJ** [comment]
Hi again

I'm glad to hear that you are still willing to work on this.

But to be honest, I fell it's really long time to wait for such a small change in the SW, which hopefully shouldn't take more than maximum half a day to implement and test.

But I do look forward for getting this feature implemented.

**Comment by KenthJ** [comment]
Hi again
I have done some changes to my Pud2GpxKmlCsv tool, now it also supports the generation of a graph containing flight data statistics, which can also been viewed in a full window, the graph can be exported as a bmp or jpg.

Furthermore the UI of the tool have been updated to look a bit more professional.

Please take a look at: https://sites.google.com/site/pud2gpxkmlcsv/

I'm still hoping you can find time to implement an easy way for customers to get pud files out of the Bebop

Br
Kenth Jensen
