### ISSUE TITLE
Problem with ARDroneSDK3 on OS X

### ISSUE THREAD

**Issue by ADeCraemer** [Parrot-Developers/ARSDKBuildUtils#29]
Hey all,
I can't install the SDK. 
I followed the manual at (https://github.com/ARDroneSDK3/Docs/blob/master/Installation/INSTALL)
But every time i use './SDK3Build.py -t iOS'
I do get the next output: 
![schermafbeelding 2015-03-31 om 17 48 55](https://cloud.githubusercontent.com/assets/9304346/7023316/9e8dafd6-dd34-11e4-99c2-316a6992733f.png)

I keep getting this Error.
![schermafbeelding 2015-03-31 om 17 50 48](https://cloud.githubusercontent.com/assets/9304346/7023336/ba9c6df2-dd34-11e4-9692-a501d2815f75.png)

But i do have autoconf version 2.69
![schermafbeelding 2015-03-31 om 17 52 59](https://cloud.githubusercontent.com/assets/9304346/7023346/cb23ccb0-dd34-11e4-9566-376f3a72f0b6.png)

I already removed and reinstalled all the external tools (git, wget, automake, autoconf, libtool)
I unlinked them and relinked them aswell multiple times..
I just don't have any clue why it doesn't work.
Any help would be much appriciated.
Greetz

**Comment by djavan-bertrand** [comment]
Hi, 

Could you post the result of your ./CheckEnv.py please ?

Thanks, 
Djavan

**Comment by ADeCraemer** [comment]
There you go
![schermafbeelding 2015-04-07 om 16 32 15](https://cloud.githubusercontent.com/assets/9304346/7025410/bccffd32-dd43-11e4-90fb-cc71516cce7f.png)

**Comment by djavan-bertrand** [comment]
We are struggling on your case :) We have the exact same autoconf here.

Could you post a gist of the whole build (including the call)? Also, could you post the result of ***autoconf --version*** in the ARSDKBuildUtils folder ?

Thanks, 
Djavan

**Comment by ADeCraemer** [comment]
You can find the gist here:
https://gist.github.com/ADeCraemer/6a72ab37c3686d68f87b
Thanks for helping me.
If you need anyhting more just ask.

Thanks in advance

**Comment by romainhuet** [comment]
Hello @djavan-bertrand,

I was trying to play with your iOS Bebop samples but unfortunately got a similar issue as @ADeCraemer during the build process with OS X 10.10.3 & autoconf 2.69. I have the same output for `./CheckEnv.py`.

Thank you!
Romain

**Comment by ADeCraemer** [comment]
I solved my problem. I reinstalled my macbook.. Thnx anyway. Gl @romainhuet

**Comment by webventil** [comment]
Hello,
I have the same issues like @romainhuet and @ADeCraemer running the compile script for iOS by using OS X 10.10.3 & autoconf 2.69. The output of `./CheckEnv.py` is identically.  
Thank you!
Arne

**Comment by webventil** [comment]
Try to delete the curl folder and start the compile script again. For me that worked.

**Comment by heefan** [comment]
[feedback]
I got error while building `curl`. Even though I went into `curl` to build manually, and re-run `./SDK3Build.py -t iOS`. It always failed for building i386.

[Solution]
delete `curl` folder and re-run `./SDK3Build.py -t iOS`.

[environment]
Mac OSX 10.10.3
Xcode 6.3.2
