### ISSUE TITLE
Unable to install iOS SDK

### ISSUE THREAD

**Issue by sylerip** [Parrot-Developers/ARSDKBuildUtils#33]
Hi,
I am new in AR Drone development. I follow the instruction and I can successfully install the OS X SDK. However, I am not able to install the iOS one. It asked me this:
Do you want to skip /Users/ipsiufai/ARSDKBuildUtils/../curl ?
1) Yes		    3) Retry		5) Show-Diff
2) No		    4) Stash/Stash-Pop	6) Reset

What should I choose??
Thz for your attention.

**Comment by webventil** [comment]
I have the same problem by compiling the libraries for iOS. The compiler stops when trying to compile libjson. Please help!
```
Building libjson (dependancy of libARMedia)
Start running iOS_BuildLibrary with args:
 -- nodeps -> False
 -- target -> iOS
 -- lib -> json
 -- inhouse -> False
 -- clean -> False
 -- debug -> False
The library libjson does not contains either an autotools or an Xcode project
Error while running iOS_BuildLibrary with args:
 -- nodeps -> False
 -- target -> iOS
 -- lib -> json
 -- inhouse -> False
 -- clean -> False
 -- debug -> False
Error while building dependancy libjson
Error while running iOS_BuildLibrary with args:
 -- nodeps -> False
 -- target -> iOS
 -- lib -> ARMedia
 -- inhouse -> False
 -- clean -> False
 -- debug -> False

```

**Comment by webventil** [comment]
I now deleted the curl and the json folder. The two projects will then be redownloaded from the compile script. After that I had no issues anymore.

**Comment by djavan-bertrand** [comment]
Thanks a lot for your feedback.
