### ISSUE TITLE
Getting the pictures from RollingSpider

### ISSUE THREAD

**Issue by katho** [Parrot-Developers/ARSDKBuildUtils#36]
Hello everyone

To transfer the pictures from the RollingSpider to my android phone I've done this sample code:

     try {
            manager = new ARDataTransferManager();
            try {
                queueList = new ARUtilsManager();
                listManager = new ARUtilsManager();
            }catch (ARUtilsException ex){
            }
            if(manager.isInitialized())
            {
                queueList.initBLEFtp(context, miBGatt, PORT);
                listManager.initBLEFtp(context, miBGatt, PORT);
                String destinyFolder = Environment.getExternalStorageDirectory().toString();

                medias = manager.getARDataTransferMediasDownloader();
                medias.createMediasDownloader(qeueList,  listManager, originPath, destinyFolder);
            
            }
        }catch (ARDataTransferException ex){
            Log.v("TRANSFER", "Failed: " + ex.toString());
        }

But it fails in the execution with this error:

java.lang.UnsatisfiedLinkError: Native method not found: com.parrot.arsdk.arutils.ARDataTransfer.nativeStaticInit();

Maybe am I doing something wrong?
What do you think about it? Can you help me out?

Thanks in advance.

**Comment by hexcone** [comment]
I encountered a similar issue with the libARStream library (http://forum.developer.parrot.com/t/resolved-android-java-lang-unsatisfiedlinkerror-in-libarstream/81)
You might be missing the following in your MainActivity.java

    System.loadLibrary("ardatatransfer");
    System.loadLibrary("ardatatransfer_android");
