### ISSUE TITLE
Bebop video stream stops for 5 seconds aproximately every minute.

### ISSUE THREAD

**Issue by lukasvst** [Parrot-Developers/ARSDKBuildUtils#37]
Hello,

I'm writing a program to control the Bebop drone and receive a videostream via ROS.
Therefore I changed the BebopDroneReceiveStream-Sample to also allow piloting the drone and added decoding with ffmpeg.
However aproximately (but not exactly) every 60 seconds the video stream just stops for over 5 seconds.

I'm sending piloting commands with a fixed frequency of 40 Hz, so that should not be a problem, however the problem seems to only occur when the drone ist flying.

Here you can see a plot of the videooutput: https://plot.ly/~lukasvst/62 (on the x-achsis, there is the time of the frame received, and the y-achsis shows the time since the last videoframe.)

I have commented out the ffmpeg-decoding and the problem still occured, so the error is not in the decoding part.

I have also recompiled the ardronesdk3 with debug output enabled, and added my own debug output (a line containing "LAGGING" when a new videoframe was received and the last frame was over 2 seconds before that).
In this file there is the (long) output of my program while flying: https://onedrive.live.com/redir?resid=fe3674ca3c9db09e!8232&authkey=!AHA0FOBGuz85jYg&ithint=file%2ctxt
To see what happened when the problem occured, you can just search for "LAGGING".

It seems like, while the lag there were (almost) no video packets lost, but the drone didn't even try to send them (as the frame number didn't make a big jump, when the first frame after the problem was received.

Do you have any idea, how this problem can be solved.
(If you need more information or want to see my code, just let me know).

Thanks in advance and best regards,
Lukas

Update: 
I have just recognized that a new sample BebopDroneDecodeStream was added, which seems to do the same thing, that I try.
As I have found out, also when using this sample, there are these 5 seconds, where no image is received at all, so the problem still occurs.

**Comment by RomanRipp** [comment]
Hello lukasvst 

I am also writing a ROS node for bebop! and Having a problem with video. Can you share your code?
