### ISSUE TITLE
Speed, distance and camera

### ISSUE THREAD

**Issue by ADeCraemer** [Parrot-Developers/ARSDKBuildUtils#38]
Hey all,

I am trying to make software for the Bebop drone. I got few questions.
- Is there a possibility to determine the speed of the drone. Eg setPitch: 10km / h or setPitch 5meter. Or fly  5 meters forward at a speed of 15km / h.
- Is it possible to render the view of the camera in real time? (Like the FreeFlight3 app) How do you do this with this SDK?
- How to take pictures and video's?

Thanks in advance,
Greetings

**Comment by djavan-bertrand** [comment]
Hi, 

You can't set the current speed, nor the distance (without doing an autonomous flight). But you have read access to the speed of the drone. You can use that even if it is not really accurate.
To do that, simply add the callback ARCOMMANDS_Decoder_SetARDrone3PilotingStateSpeedChangedCallback to receive the 
- Speed on the x axis (when drone moves forward, speed is > 0) (in m/s)
- Speed on the y axis (when drone moves to right, speed is > 0) (in m/s)
- Speed on the z axis (when drone moves down, speed is > 0) (in m/s)

It is possible to render the view of the camera in real time. The stream is h264 encoded. You can see an example of displaying the video in the Samples for Unix. One of them gives the stream to mplayer so it can decode it and display it. The other one decode the stream with ffmpeg and give the decoded frames to mplayer.

To take picture or video, simply send ARCOMMANDS_Generator_GenerateARDrone3MediaRecordPicture or ARCOMMANDS_Generator_GenerateARDrone3MediaRecordVideo (with mass_storage_id param set to 0).

Regards, 
Djavan

**Comment by alexcherpi** [comment]
Hi, 
If I'm using Freeflight3 on the Smartphone 'oneplus one' the video streaming is continous with almost no delay. But if I'm using my computer (Lenovo W540) using the Unix sample code 'BebopDroneDecodeStream' or 'BebopDroneReceiveStream' the delay is huge and the stream not continous. The quality is much worse.

What are the way to improve the quality on the computer ?

Regards,
Alex

**Comment by ADeCraemer** [comment]
Thanks for the info.

But still got a question. Based on what you said it aint possible to make some kind of hardcoded route? In which the drone has to fly 5 meter forwards then turn 90 degrees to the left fly again 3 meter forwards. Is this possible to program?

Regards,
Arne

**Comment by djavan-bertrand** [comment]
Not that I am aware of. 
If you really need to do it before the next firmware release (in the coming weeks), you can maybe look at [Paparazzi](https://wiki.paparazziuav.org/wiki/Main_Page). I can't provide support on it, but I think they support the bebop. It is not very easy, so maybe a small wait is better ;)

Regards,
Djavan

**Comment by djavan-bertrand** [comment]
@alexcherpi : If you use BebopDroneReceiveStream right after BebopDroneDecodeStream or Freeflight, streaming will be bad, because we don't send piloting commands in this sample. Piloting commands are used by the Bebop to determine the quality of wifi link. So you will need to turn off your drone before running BebopDroneReceiveStream. DecodeStream is better implemented as it has a frame queue. So I would recommend using this one.

@ADeCraemer : It is possible to program it, yes, but it won't be very accurate. For example, if you know your drone's current speed is 5 m/s, then, moving during 10 seconds, you can think you have flew 50 meters.

**Comment by CesarRN** [comment]
Hello ADeCraemer, you can find a topic about video streaming on iOS
https://github.com/ARDroneSDK3/Samples/issues/25#issuecomment-86785163

Regards.
