### ISSUE TITLE
Possibility to cancel a landing

### ISSUE THREAD

**Issue by KenthJ** [Parrot-Developers/ARSDKBuildUtils#39]
Hi there

With the current implementation there is no possibilities to cancel a landing once it has been initiated.
Only the RTH functionality can be cancelled.

This can cause really dangerous situations if the user pressed the landing button by an mistake, for an example if he wants to press RTH over water or other inaccessible areas and by mistake pressed the land button.
Instead it should work like if you press the landing button a second time, or presses something else like RTH or the throttle to make the drone climb to a higher altitude, the landing should be cancelled.

This has been discussed several times on the US Parrot Bebop forum and on the Bebop owners group on Facebook, where several users, including myself, have been close to loosing or destroying their Bebop due to this.

**Comment by Grosbof** [comment]
This discussion was closed, but is it because a solution already exist, or because it's worked on, or because it was simply ignored?
