### ISSUE TITLE
[Android] Default action when connection is lost

### ISSUE THREAD

**Issue by sylvioalves** [Parrot-Developers/ARSDKBuildUtils#41]
Hi, 
We have created an Android application and currently it supports Bebop, Rs and Js.
Tthere is an "issue" that I would like to bring up.
We found out that after sending a PCMD, Bebop for instance holds its value forever and maintain is movement based on that PCMD (like moving forward). 
If the application sends a PCMD (only zeroes), it stops and keeps hovering still. 

However, let's think of a mobile application. If application crashes or wifi connection is lost or anything else happens, that 1st PCMD will be executed forever (well, at least until it run out of battery...). My point of view is that ARDroneSDK3 could have a ACK from application to the Controller and also a Default action when those Acks stops coming. If Bebop stops receiving those acks (or when connection is lost), a default action could be trigggered (or PCMD could be set automatically to zeros).

Please, can you guys comment on this? I understand that this kind of request is not related to the application but to firmware team.

Thanks!

BR,
Sylvio Alves

**Comment by djavan-bertrand** [comment]
Hi, 

On which version are you experiencing this behaviour ?
The drone keeps the last PCMD values during a very short period, after what it gets back to hovering.

A way to test that behaviour could be, in the [BebopDronePiloting sample](https://github.com/ARDroneSDK3/Samples/tree/master/Android/BebopDronePiloting) : 
- changing [the initial yaw value of the data to a custom value (50 for example)](https://github.com/ARDroneSDK3/Samples/blob/master/Android/BebopDronePiloting/app/src/main/java/com/parrot/bobopdronepiloting/DeviceController.java#L887)
- launch app
- connect to a Bebop
- take off (the Bebop should turn around)
- switch off the wifi or kill app
- The Bebop should now hover

I've tested with the 1.98.10 firmware version and this is Ok.

Best regards, 
Djavan
