### ISSUE TITLE
How can I build ARSDK3 on cygwin

### ISSUE THREAD

**Issue by dreamkeep** [Parrot-Developers/ARSDKBuildUtils#42]
it was error:

$ ./CheckEnv.py
-- Checking if your environment will build the ARSDK for different platforms --

[[ OK:Should work, FA:Won't work, NT:Not tested, may work ]]

NT:Generic             : Unknown platform `cygwin_nt-6.2-wow`, the target `Generic` has only been tested on ['darwin', 'linux']
                      Missing binary `jar`
ERROR !

FA:Basic configuration is not met, the SDK3Build.py script will probably fail even before trying to build a target. Fix errors for virtual target "Generic" before launching the script

so how can I build the ARSDK3 on cygwin? tks

**Comment by dreamkeep** [comment]
and I configure the NDK, android SDK, then I run ./SDK3Build.py -t  Android
result is:


Status :
 --> Legend : FA:FAIL OK:PASS ND:NOT_BUILT NR:NOT_REQUESTED NA:NOT_AVAILABLE
 --> Binaries are postfixed with `*`
 --> Postbuild scripts  are postfixed with `+`

NR:Unix       : NR:curl                NR:json                NR:ARSAL               NR:ARDiscovery         NR:ARNetworkAL         NR:ARCommands          NR:ARNetwork           NR:ARStream
                NR:ARMavlink           NR:ARUtils             NR:ARDataTransfer      NR:ARUpdater           NR:ARMedia

NR:iOS        : NR:curl                NR:json                NR:ARSAL               NR:ARDiscovery         NR:ARNetworkAL         NR:ARCommands          NR:ARNetwork           NR:ARStream
                NR:ARMavlink           NR:ARUtils             NR:ARDataTransfer      NR:ARUpdater           NR:ARMedia

FA:Android    : FA:curl                FA:json                FA:ARSAL               ND:ARDiscovery         ND:ARNetworkAL         ND:ARCommands          ND:ARNetwork           ND:ARStream
                ND:ARMavlink           ND:ARUtils             ND:ARDataTransfer      ND:ARUpdater           ND:ARMedia

End of build
-- Errors were found during build ! --
Build took 6m 48s

**Comment by TelmoGaspar** [comment]
Iḿ have the same problem "Missing binary jar" in linux terminal!
Im very newby to linux , any one can help how to fix this jar problem?

**Comment by alexcherpi** [comment]
I solved this problem by installing default-jdk
'apt-get install default-jdk' or 'sudo apt-get install default-jdk'
Best, Alex

**Comment by TelmoGaspar** [comment]
Thank you Alex It solved

**Comment by djavan-bertrand** [comment]
Thanks @alexcherpi for your feedback.

**Comment by kahvel** [comment]
In windows it is not possible to use apt-get. Have to do:
`export PATH=$PATH:"/cygdrive/c/Program Files/java/jdk.1.8.0_60"`
