### ISSUE TITLE
[Android] Sometimes Bebop video stream lags to start

### ISSUE THREAD

**Issue by sylvioalves** [Parrot-Developers/ARSDKBuildUtils#44]
Hi, 

I am not sure if this an issue of my coding but it happens that after setting Bebop video streaming to true, sometimes it takes from 5~30s to get callbacks from the method below (which allows application to show video content..). Most of the time if starts after 1~2 seconds, which is fine by me.

public ARNativeData didUpdateFrameStatus(ARSTREAM_READER_CAUSE_ENUM cause, final ARNativeData currentFrame, final boolean isFlushFrame,
                        int nbSkippedFrames, int newBufferCapacity)

Does anyone have a hint?

Thanks.

Sylvio

**Comment by ismailo200** [comment]
Hi ,
Sorry i don't an answer to ur question , but i wanna ask you how do you do to get video streaming ?
Thanks
