### ISSUE TITLE
How to calculate the average speed of the drone?

### ISSUE THREAD

**Issue by ADeCraemer** [Parrot-Developers/ARSDKBuildUtils#45]
Hey all,

I would like to know how I can calculate the average speed of the drone. 
I do use the ARCOMMANDS_Decoder_SetARDrone3PilotingStateSpeedChangedCallback method to get to know the x-as speed. But with that callback method you do get the speed at that moment. 
My problem is that I would like to know the average speed after 2-3 seconds of flying. How can I calculate that?
At first I tried to counte all received speed and i diveded the total speed by x (times there has been a speed added to the total sum). But this isn't correct.

Thnx in advance!

**Comment by sylvioalves** [comment]
Hi, 

Although my reply is not what you really want, it goes:

Maybe you could get a resultant speed from the 3-axis using an operation like below:
final_speedy = sqrt(speedy_x^2 + speedy_y^2 + speedy_z^2);

Create a MovingAverage class that (you can find it on google) and feed it with the final_speedy value every time it updates. MovingAverage window of 2~3 seconds can be worked out inside this class, where if no new final_speedy is fed for a few milliseconds, you just add zero to it..

Regards,
sirvo
