### ISSUE TITLE
ReturnToHome is using a very low speed

### ISSUE THREAD

**Issue by KenthJ** [Parrot-Developers/ARSDKBuildUtils#47]
When pressing ReturnToHome the drone is flying with a very low speed, seems to be only one third of the full speed.

This is not ideal if you fly your drone so far away that you loose wifi connection to it, and it flyes very slowly back to you, then there is a risk that it will run out of battery before it get back to you.

When I press RTH I would also like the drone to get back to me as fast as possible.

When the drone gets closer to the take off position it is okay to slow down the speed, but if the distance of the drone and the controller is more than e.g. 100 meter, it should fly at full speed

**Comment by JeromeBouvard** [comment]
can you please move the topic to http://forum.developer.parrot.com
thanks ! :)
