### ISSUE TITLE
x86_64 slice for iOS binaries?

### ISSUE THREAD

**Issue by timsee** [Parrot-Developers/ARSDKBuildUtils#48]
Hey Parrot,

I've been working on an iOS applicatoin that uses this SDK. As part of our development cycle we put the app through pretty rigorous unit testing. 

When building for simulator, iOS uses i386 and x86_64. We are able to use the i386 slices, but the x86_64 slices are unavailable, which makes testing on simulated iPads slightly more difficult. Our current workaround is to use a simulation of an older iPad model for logic testing. Then when we need to test the application on a more recent simulated iOS device we remove the parrot frameworks and test only a portion of our codebase.

It would be pretty convenient if there was a way to compile so that x86_64 was included in the binary. Is there any way to do this?

Thanks,
Tim

**Comment by djavan-bertrand** [comment]
Hi, 
To enable the build for x86_64, you will need two things:
- Replace the curl revision in [repos.xml](https://github.com/Parrot-Developers/ARSDKBuildUtils/blob/master/repos.xml#L97) `curl-7_36_0-arsdk` by `curl-7_36_0-arsdk-branch`
- Add the architecture in the [build iOS library script](https://github.com/Parrot-Developers/ARSDKBuildUtils/blob/master/Utils/Python/iOS_BuildLibrary.py#L111):  `{ 'arch':'x86_64', 'platform':'iPhoneSimulator', 'minos':'ios-simulator' }`<br/>
    The block should look like that : <br/>
    ```KnownArchs = [ { 'arch':'armv7', 'platform':'iPhoneOS', 'minos':'iphoneos' },
                                  { 'arch':'armv7s', 'platform':'iPhoneOS', 'minos':'iphoneos' },
                                  { 'arch':'arm64', 'platform':'iPhoneOS', 'minos':'iphoneos' },
                                  { 'arch':'i386', 'platform':'iPhoneSimulator', 'minos':'ios-simulator' },
                                  { 'arch':'x86_64', 'platform':'iPhoneSimulator', 'minos':'ios-simulator' }]```

Then, it should be ok. 

We will soon replace the build for the 32bit simulator by the 64bit simulator. We think having both is too long to compile for the usage.

Tell me if you have any problems. 
Best regards, 
Djavan

**Comment by timsee** [comment]
Awesome,

The instructions worked as intended and worked on the first try :)

I can see what you mean about the long compile time for the amount of usage people would get out of it. I cannot speak for everyone but I know that we personally will not be using the i386 slices at all anymore since theres no longer a need.

Thanks again!

~Tim
