### ISSUE TITLE
Bebop video parameters

### ISSUE THREAD

**Issue by RomanRipp** [Parrot-Developers/ARSDKBuildUtils#49]
Hi all, I am creating a bebop node for ROS (Robotics Operating System).
For video I was able to receive it and play it with mplayer as in example. Now I need to publish video topic on ROS, I want to use sensor_msgs::Image so other ros components can use video stream from Bebop. 
my problem is I need to initialize the  sensor_msgs::Image, and for this I need the following: 
   
uint32 height         # image height, that is, number of rows
uint32 width          # image width, that is, number of columns
string encoding     # Encoding of pixels -- channel meaning, ordering, size
                             # taken from the list of strings in include/sensor_msgs/image_encodings.h
uint8 is_bigendian    # is this data bigendian?
uint32 step           # Full row length in bytes
uint8[] data          # actual matrix data, size is (step * rows)

Do you have any idea where I can get such values. May be you know if someone already did bebop video to ROS conversion ???

**Comment by djavan-bertrand** [comment]
Hi, 

in the frameCompleteCallback (or, better, in the Decode_RunDataThread in the BeboDroneDecodeSample) you have access to a rawFrame.
In this rawFrame you have the information about the data (called data) and its size (called size). 
The encoding is YUV422.
All others params should be (and can be) guessed by the data. As you can see, in the BebopDroneDecodeStream sample, the DecodeManager class has no info about width & height and yet it returns it (see [here](https://github.com/Parrot-Developers/Samples/blob/master/Unix/BebopDroneDecodeStream/DecoderManager.c#L430)).

Regards, 
Djavan

**Comment by RomanRipp** [comment]
Hello, thank you for your answer. I do not want to decode stream, because It will be passed to other applications that should handle decoding. However the list of supported encodings is as follows: http://docs.ros.org/diamondback/api/sensor_msgs/html/image__encodings_8h_source.html
Given this what should I convert my video to one of supported encodings? if yes what are performance implications? Can I get video from bebop encoded differently? what is the fastest conversion I can do? is there library for this? 

Thank you ))

**Comment by JeromeBouvard** [comment]
can you please move the topic to http://forum.developer.parrot.com
thanks ! :)
