### ISSUE TITLE
[Android] Failing to build for Android

### ISSUE THREAD

**Issue by JKalash** [Parrot-Developers/ARSDKBuildUtils#52]
running SDK3Build.py -t Android failing on all libraries except json.
Output error: 

Error while running Android_BuildLibrary with args:
-- nodeps -> False
-- lib -> <Any library>
-- requestedArchs -> None
-- inhouse -> False
-- clean -> False
-- isLib -> True
-- stripVersionNumber -> True

I made sure that Android_sdk_path and Android_ndk_path are set and Path variable points to all 3 android toolchain architectures.

Anything I'm missing here?

**Comment by JeromeBouvard** [comment]
can you please move the topic to http://forum.developer.parrot.com
thanks ! :)
