### ISSUE TITLE
Documentation non-existent

### ISSUE THREAD

**Issue by tkdberger** [Parrot-Developers/ARSDKBuildUtils#55]
I would like to simply point out this comment that was made in response to a pointer for "documentation". A Moderator pointed them to this repo and [the parrot forum](http://forum.parrot.com/english/)
(Note that this is pulled straight of Parrot's blog and is not my comment.)
>REALLY??!?!?!?! 
>That's your answer??

>You DO REALIZE that the "information" regarding USING the "SDK" actually does not exist at either of these sources?? And considering 1 of these mentioned sources is where the SDK is obtained, then anyone who even has the SDK, knows about the first link, and if they are asking for documentation, how can you think they would 'all-of-a-sudden' find it helpful??

>Besides a cryptic installation instructions, there is ABSOLUTELY NO USAGE DOCUMENTATION!!

>They claim there are "samples". And TECHNICALLY they are correct, however!! The samples are just random source files, and if you add them to your IDE (I'm on Max using XCode), they the samples are trying to link to additional files not in SDK or samples file, making the samples useless!!!

>Almost ALL samples generally provided with an SDK of any type, is a COMPLETE sample program, that can be instantly compiled and tried on the device in question, ESPECIALLY if it is an SDK that interacts or opens communication with a piece of hardware! Then as a programmer, you take bits and pieces as you see fit for your own project.

>The previous Parrot SDK for the ARDrone2.0 was GREAT!!!!!

>It had FANTASTIC documentation!! Right from real basics (proper rotation, yaw, pitch, etc), to pain staking details regard establishing connections to the drone, how to accept and send data, CRAZY detail on the important methods to use with full explanations and examples.

>It also came with the FULL FreeFlight2 project file!!! I was able to open it up in XCode, and there it was, FreeFlight2, every screen, every line of code, if i actually had the ARDrone2 and not BeBop, i could have complied it and ran on my actual iPhone without even touching a line of code.

>Instead, with the SDK3, after 2 weeks, I'm sitting here without even a vague STARTING POINT!!.

>No documentation: They include a 'html' files under the 'Docs" folder, but this is NOT DOCUMENTATION!! It is an automatically generated set of web pages that output the content of source files in list form!!

>NO ONE from Parrot sat down and wrote ANY documentation, and descriptions that show in those files, were just pulled automatically as well from comments in the source code.

>In fact, if you have the source code which is in the SDK, it is actually EASIER to browser through the source code to read the comments, rather than in that stupid automatically generated list, which is housed in a clumsy interface which is buggy (i guess all in the Parrot family!)

>There's not even a quick start file, just to say something like:

>1) Import xxx.xxx file into your code.
>2) Create xxx object with xxx constructer to connect to the Drone
>3) Call xxx method to send "TakeOff Command"

>THERE JUST NOTHING!!! In case it's not obvious after reading this far, THIS IS GOD DAMN INFURIATING!!! 

It would be nice to see some docs written for those of us who have no idea what to do.

**Comment by djavan-bertrand** [comment]
Hi tkdberger, 

You can find documentation about how to use the SDK [here](http://developer.parrot.com/docs/bebop/).
Also, the forum where you can ask questions and discuss with other developers about the SDK is [this one](http://forum.developer.parrot.com/), not the one in your comment.

Hope you'll find this useful, 
Best regards, 
Djavan

**Comment by tkdberger** [comment]
Why thank you. Now let's see if I can start using this for my Jumping Sumo
like it says it can...
